# Generated by Django 4.1.13 on 2024-08-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('user', models.CharField(max_length=255)),
                ('orderNo', models.CharField(max_length=255)),
                ('model', models.TextField()),
                ('error', models.TextField()),
                ('supplier', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('errorSource', models.TextField()),
                ('detectionMethod', models.TextField()),
                ('action', models.TextField()),
                ('result', models.CharField(max_length=255)),
                ('actionForRepeat', models.TextField()),
                ('customer', models.ManyToManyField(to='event_reporting.customer')),
            ],
        ),
    ]
