# Generated by Django 4.1.13 on 2024-08-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reporting', '0002_alter_event_action_alter_event_actionforrepeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='customer',
            field=models.ManyToManyField(blank=True, to='event_reporting.customer'),
        ),
    ]
